# Generated by Django 5.0.1 on 2024-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('qualification', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('expertise', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=255)),
                ('skills', models.TextField()),
            ],
        ),
    ]
